name: Continuous Integration

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
      timeout_minutes:
        required: false
        type: number
        default: 15
    secrets:
      github-token:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Code Lint
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Install git
        run: sudo apt update && sudo apt install -y git

      - name: Debug event name
        run: echo ${{ github.event_name }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.head_ref }}

            #- name: Checkout PR (from fork or branch)
            #  if: github.event_name == 'pull_request'
            #  uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            #  with:
            #    ref: refs/pull/${{ github.event.pull_request.number }}/head

            #- name: Checkout push branch (main or other)
            #  if: github.event_name != 'pull_request'
            #  uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            #  with:
            #    ref: ${{ github.ref }}

      - name: Check branch name
        run: |
          echo ${{ github.ref }}
          git rev-parse --abbrev-ref HEAD

      - name: Where am I
        run: |
          pwd
          ls -la

      - name: Run test
        run: cat ./file.txt
