name: Validate PR title

on:
  pull_request:
    branches:
      - main
      - release/*
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
        with:
          types: |
            breaking
            chore
            ci
            docs
            feat
            fix
            refactor
            security
            style
            test
