name: Validate PR title

on:
  pull_request:
    branches:
      - main
      - release/*
    types:
      - opened
      - edited
      - synchronize
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  main:
    runs-on: "${{ inputs.runs_on }}"
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ ssecrets.REPO_GITHUB_TOKEN }}
        with:
          types: |
            breaking
            chore
            ci
            docs
            feat
            fix
            refactor
            security
            style
            test
